### ISSUE TITLE
Add support for handling description and long_description

### ISSUE THREAD

**Issue by benoit74** [openzim/python-scraperlib#110]
The following logic could be shared among Python scrapers for handling `description` and `long_description` length and the distinction between user-provided and default values:
- three parameters are provided to the function:
  - a default `description` (typically retrieved online from some metadata)
  - an optional user-defined `description` (typically a CLI arg)
  - an optional user-defined `long_description` (typically a CLI arg)
- the function returns:
  - a `description`
  - an optional `long_description`
- if set, the two user-defined values are checked to not exceed ZIM maximum length ; an error is thrown otherwise ; if ok, they are returned
- if user-defined `description` is not set, it is computed based on the default description (truncated if needed)
- if user-defined `long_description` is not set and default description has been truncated (because it was too long for the description field), the `long_description` is computed based on the default description (truncated if needed), otherwise it is not set

Code is almost already ready in [kolibri](https://github.com/openzim/kolibri/blob/3c3aeb1e2e51b0d9cea7f327c57919f307583218/src/kolibri2zim/scraper.py#L944-L962)

**Comment by rgaudin** [comment]
Where would this land in the API?

**Comment by benoit74** [comment]
In a function named `compute_descriptions` in `src/zimscraperlib/inputs.py`?

**Comment by rgaudin** [comment]
👍
