### ISSUE TITLE
Add support for SVG conversion (e.g. to convert favicon) and confirm probing is OK

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-scraperlib#113]
Our image functions all assume bitmap input or output. Should we support vector formats as well (SVG's the only open and widespread one I think)? If so, should it be using different API or should this be handled transparently?

**Comment by holta** [comment]
Browsers support SVG 1.1:
https://caniuse.com/svg

SVG 2 does not yet seem to be supported by browsers:
https://svgwg.org/svg2-draft/

Never easy to align with "all" browsers... but if attainable... Awesome!

**Comment by kelson42** [comment]
Would nice indeed, but maybe we can wait the first use case to do it.

**Comment by benoit74** [comment]
It is quite common with zimit website to have a favicon in SVG format. This fails to be processed currently.

**Comment by kelson42** [comment]
We should go to have a smooth conversion to the expected PNG format.

**Comment by benoit74** [comment]
I propose to use following test set to choose the SVG library:
- https://solar.lowtechmagazine.com/icons/sun.svg
- https://docs.python.org/3/_static/py.svg
- https://www.gstatic.com/images/icons/material/apps/fonts/1x/catalog/v5/favicon.svg
- https://www.solidarite-numerique.fr/wp-content/themes/snum-v2/images//ico/favicon.svg
- https://summerofcode.withgoogle.com/assets/favicons/safari-pinned-tab.svg

**Comment by kelson42** [comment]
My experience (mostly with Mediawiki) is with librsvg. It is already a few years old, but work fine.

**Comment by benoit74** [comment]
Just changed the title to confirm that this issue will focus on conversion (todo) + probing (probably already working with PIL). SVG optimization is already tracked in https://github.com/openzim/python-scraperlib/issues/80 and will need a different tooling.
