### ISSUE TITLE
Add support for Python 3.12

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-scraperlib#118]
We are using `pkg_resources` which have been removed

**Comment by benoit74** [comment]
Could you (again, sorry) point me to where it is used in scraperlib?

**Comment by rgaudin** [comment]
I can't find it!

**Comment by benoit74** [comment]
CI found it for us: https://github.com/openzim/python-scraperlib/actions/runs/7802293999/job/21279404181?pr=127 🤣 

The problem is in the i639 package in fact.

**Comment by benoit74** [comment]
Sorry, "iso-639"

**Comment by benoit74** [comment]
FYI, I'm trying a move to https://pypi.org/project/iso639-lang/ which seems maintained and supporting everything we need.

**Comment by rgaudin** [comment]
OK; I remember that was a petty reason to use it but I suppose if tests pass it's OK
