### ISSUE TITLE
Add a less generic subsclass of StaticItem

### ISSUE THREAD

**Issue by benoit74** [openzim/python-scraperlib#130]
As discussed in https://github.com/openzim/python-scraperlib/issues/109, we can benefit from creating a less generic subclass of StaticItem with more strongly typed arguments than the very generic `**kwargs` we have in StaticItem.

This less generic class would serve >80% of the scraper needs.

**Comment by benoit74** [comment]
@rgaudin do you think there is something left to do on this issue after #132 last changes? 

I had a look at all openZIM codebase and did not find anything which is not covered. 

Most scrapers are using either `add_item_for` or `add_redirect`

The only thing we forgot to perform is the modification of `add_item_for` to use new `StaticItem` parameters. But this is not really related to this issue.

**Comment by rgaudin** [comment]
I agree ; we can close this

**Comment by benoit74** [comment]
Fixed by #132
