### ISSUE TITLE
`Archive.get_item` type hint is wrong

### ISSUE THREAD

**Issue by benoit74** [openzim/python-scraperlib#196]
`Archive.get_item` type hint suggest that it returns a `zimscraperlib.zim.items.Item` while in fact it return a `libzim.writer.Item`.

We should either fix the code (preferably) or the type hint (would be sad)

**Comment by rgaudin** [comment]
Why would it be sad to fix the signature? Is this type useless? If so the issue should be about deleting it rather than this collateral

**Comment by benoit74** [comment]
The `zimscraperlib.zim.items.Item` type is useful, so this is why I do not want to fix the signature which is correct. But then the code should really return such an object, and not a `libzim.writer.Item`.

**Comment by benoit74** [comment]
The problem is that today I can't use `item.mimetype` because the type checker complains, and I can't use `item.get_mimetype()` because it fails at runtime.

**Comment by rgaudin** [comment]
Ah I thought it was the other way around. Indeed we should return it.

**Comment by benoit74** [comment]
In fact type hint is wrong, it is a writing item. We should fix type hint with libzim reading item which is sufficient.

**Comment by benoit74** [comment]
Fixed by https://github.com/openzim/python-scraperlib/pull/202
