### ISSUE TITLE
Add `get_content` to `zimscraperlib.zim.items.Item`

### ISSUE THREAD

**Issue by benoit74** [openzim/python-scraperlib#197]
We often need to get item content in tests, so a `get_content` method would help a lot.

**Comment by rgaudin** [comment]
What do you mean exactly by _in tests_? pylibzim unit tests suite? Other project unit tests ? Or just playing with REPL?

I think creating a custom `get_content` function is fine for the first ones. It's annoying for the last one though.

I think doing so we be in opposition to our current pure-wrapper moto and the real issue being that our friendly zim wrapper is tied to the heavy zimscraperlib.

**Comment by benoit74** [comment]
By **in tests** I meant in other project unit tests.

> I think doing so we be in opposition to our current pure-wrapper moto and the real issue being that our friendly zim wrapper is tied to the heavy zimscraperlib.

I don't get this point, this is a scraperlib issue, I suggest to add this method only in scraperlib. In python-libzim we can use `item.content` and it works fine.

**Comment by rgaudin** [comment]
Sorry I keep mixing both today 🤪 I think I'm used to use `scraperlib` and `zimscraperlib` so anytime I see `python-` I think it refers to pylibzim. I did not properly read the title and thought this was about `Archive`. Let me find my glasses 👓

What would this `get_content` return?

**Comment by benoit74** [comment]
The `content` of libzim `Item`?

**Comment by rgaudin** [comment]
Are we still talking about https://github.com/openzim/python-scraperlib/blob/main/src/zimscraperlib/zim/items.py#L28 ?

What's the `content` then ?
