### ISSUE TITLE
Add `is_valid_langcode()` utility method

### ISSUE THREAD

**Issue by anshulxyz** [openzim/python-scraperlib#84]
As seen requested here https://github.com/openzim/cms/pull/37#discussion_r759310873

Add `is_valid_langcode()` utility method to `i18n.py`, that returns a boolean on wether something is a valid language code or not

- Support multiple language code like:
    - ISO 639-1 (alpha2)
    - ISO 639-2 (alpha3)

**Comment by rgaudin** [comment]
`i18n.get_language_details` with `failsafe` already serves this purpose.

We now have `i18n.is_valid_iso_639_3` that we use. I'm in favor of having a `is_valid_iso_639_2` as well as soon as the need arise.
