### ISSUE TITLE
Extra Empty metadata 

### ISSUE THREAD

**Issue by rgaudin** [openzim/python-scraperlib#87]
ZIMs made with zimwriterfs-like `zimscraperlib.zim.filesystem:make_zim_file()` appear to set non-set metadata to an empty string instead of not setting said metadata.

See:
- http://library.kiwix.org/raw/bayardcuisine_fr/meta/Source
- http://library.kiwix.org/raw/bayardcuisine_fr/meta/Flavour
- http://library.kiwix.org/raw/mesptitesquestions_fr/meta/Source

It seems zimwriterfs 2.0.1-1 was doing the same:
- http://library.kiwix.org/raw/gutenberg_ale_all/meta/Flavour
- http://library.kiwix.org/raw/gutenberg_ale_all/meta/Source
But zimwriterfs 3.1.0 is not affected:
- http://library.kiwix.org/raw/eleda_fr/meta/Source

**Comment by rgaudin** [comment]
See #95

**Comment by kelson42** [comment]
Clearly bugs IMO

**Comment by rgaudin** [comment]
Fixed in 3.0.0
